name: scan-image
description: Scan a Docker image for vulnerabilities using Trivy

inputs:
  image-ref:
    description: The Docker image to scan
    required: true
  fail-on-vulnerability:
    description: Fail the workflow if vulnerabilities are found
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: aquasecurity/trivy-action@e368e328979b113139d6f9068e03accaed98a518 # 0.34.1
      with:
        image-ref: ${{ inputs.image-ref }}
        exit-code: ${{ inputs.fail-on-vulnerability == 'true' && '1' || '0' }}
        ignore-unfixed: true
        format: sarif
        output: trivy-results.sarif
    - uses: github/codeql-action/upload-sarif@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # v4.31.9
      if: always()
      with:
        sarif_file: trivy-results.sarif
