name: scan-image
description: Scan a Docker image for vulnerabilities using Trivy

inputs:
  image-ref:
    description: The Docker image to scan
    required: true
  fail-on-vulnerability:
    description: Fail the workflow if vulnerabilities are found
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
      with:
        image-ref: ${{ inputs.image-ref }}
        exit-code: ${{ inputs.fail-on-vulnerability == 'true' && '1' || '0' }}
        ignore-unfixed: true
        format: sarif
        output: trivy-results.sarif
    - uses: github/codeql-action/upload-sarif@45775bd8235c68ba998cffa5171334d58593da47 # v3.28.15
      if: always()
      with:
        sarif_file: trivy-results.sarif
