name: nix-image
description: Build a Docker image using Nix and optionally push it to a registry.

inputs:
  token:
    description: The GitHub token to use for authentication
    required: false
  push:
    description: Push the image to the registry
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: DeterminateSystems/nix-installer-action@v17
      with:
        determinate: true
    - uses: DeterminateSystems/flakehub-cache-action@v1
    - uses: DeterminateSystems/flake-checker-action@v9
    - shell: bash
      run: nix build .#dockerImage
    # TODO: use some sort of sane tag..
    - shell: bash
      id: image-info
      run: |
        echo "name=$(nix eval --raw .#dockerImage.imageName)"
        echo "ref=$(nix eval --raw .#dockerImage.imageRefUnsafe)"
    - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      if: ${{ inputs.push == 'true' }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    - shell: bash
      if: ${{ inputs.push == 'true' }}
      run: nix run .#dockerImage.copyToRegistry

outputs:
  image-name:
    description: Image name
    value: ${{ steps.image-info.outputs.image-name }}
  image-ref:
    description: Image reference
    value: ${{ steps.image-info.outputs.image-ref }}
