name: nix-image
description: Build a Docker image using Nix and optionally push it to a registry.

inputs:
  token:
    description: The GitHub token to use for authentication
    required: false
  push:
    description: Push the image to the registry
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: DeterminateSystems/nix-installer-action@v17
      with:
        determinate: true
    - uses: DeterminateSystems/flakehub-cache-action@146f476c94460cb634f9ade79470fcbc3f7e5b36 # v1
    - uses: DeterminateSystems/flake-checker-action@v9
    - shell: bash
      run: nix build .#dockerImage
    - shell: bash
      id: image-info
      run: |
        echo "arch=$(dpkg --print-architecture)" >> "$GITHUB_OUTPUT"
        echo "name=$(nix eval --raw .#dockerImage.imageName)" >> "$GITHUB_OUTPUT"
    - uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
      id: meta
      with:
        images: ${{ steps.image-info.outputs.name }}
        tags: |
          type=sha,suffix=-${{ steps.image-info.outputs.arch }}
    - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      if: ${{ inputs.push == 'true' }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    - shell: bash
      if: ${{ inputs.push == 'true' }}
      run: nix run .#copyDockerImage

outputs:
  image-name:
    description: Image name
    value: ${{ steps.image-info.outputs.name }}
  image-ref:
    description: Image reference
    value: ${{ steps.meta.outputs.tags }}
