name: build-docker-image
description: Build a Docker image and run security scans

inputs:
  token:
    description: The GitHub token to use for authentication
    required: false
  push:
    description: Push the image to the registry
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
      id: meta
      with:
        images: ghcr.io/${{ github.repository_owner }}/ubuntu
        tags: |
          type=sha
          type=edge
          type=edge,suffix=-{{date 'X'}}
    - uses: depot/setup-action@b0b1ea4f69e92ebf5dea3f8713a1b0c37b2126a5 # v1.6.0
    - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      if: ${{ inputs.push == 'true' }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    - uses: depot/build-push-action@636daae76684e38c301daa0c5eca1c095b24e780 # v1.14.0
      id: build
      with:
        context: .
        project: h8rjlfhzg5
        platforms: linux/amd64,linux/arm64
        load: ${{ inputs.push == 'false' }}
        push: ${{ inputs.push == 'true' }}
        sbom: true
        provenance: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - uses: winterjung/split@7f51d99e7cc1f147f6f99be75acf5e641930af88 # v2.1.0
      id: split
      with:
        msg: ${{ fromJSON(steps.build.outputs.metadata)['image.name'] }}
        separator: ","
    - uses: vexxhost/github-actions/scan-image@main
      with:
        image-ref: ${{ steps.split.outputs._0 }}
        fail-on-vulnerability: ${{ inputs.push == 'true' && 'true' || 'false' }}

outputs:
  image-name:
    description: The name of the image built
    value: ${{ steps.split.outputs._0 }}
