name: build-docker-image
description: Build a Docker image and run security scans

inputs:
  token:
    description: The GitHub token to use for authentication
    required: false
  context:
    description: The context for the Docker build
    required: false
    default: '.'
  image-ref:
    description: The Docker image to build
    required: true
  tags:
    description: List of docker/metadata-action tags
    required: false
    default: |
      type=sha
      type=edge
      type=edge,suffix=-{{date 'X'}}
  build-args:
    description: Build arguments for the Docker image
    required: false
  push:
    description: Push the image to the registry
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5.9.0
      id: meta
      with:
        images: ${{ inputs.image-ref }}
        tags: ${{ inputs.tags }}
    - uses: depot/setup-action@b0b1ea4f69e92ebf5dea3f8713a1b0c37b2126a5 # v1.6.0
    - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      if: ${{ inputs.push == 'true' }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    - uses: depot/build-push-action@636daae76684e38c301daa0c5eca1c095b24e780 # v1.14.0
      id: build
      with:
        project: h8rjlfhzg5
        context: ${{ inputs.context }}
        platforms: linux/amd64,linux/arm64
        build-args: ${{ inputs.build-args }}
        load: ${{ inputs.push == 'false' }}
        push: ${{ inputs.push == 'true' }}
        sbom: true
        provenance: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - uses: winterjung/split@7f51d99e7cc1f147f6f99be75acf5e641930af88 # v2.1.0
      id: split
      with:
        msg: ${{ fromJSON(steps.build.outputs.metadata)['image.name'] }}
        separator: ","
    - uses: vexxhost/github-actions/scan-image@main
      with:
        image-ref: ${{ steps.split.outputs._0 }}
        fail-on-vulnerability: ${{ inputs.push == 'true' && 'false' || 'true' }}

outputs:
  image-name:
    description: The name of the image built
    value: ${{ steps.split.outputs._0 }}
