name: image

on:
  workflow_call:
    inputs:
      image-ref:
        type: string
        required: true
      tags:
        type: string
        required: false
        default: |
          type=sha
          type=edge
          type=edge,suffix=-{{date 'X'}}
      build-args:
        type: string
        required: false
      push:
        type: boolean
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      security-events: write
    steps:
      - uses: vexxhost/github-actions/build-docker-image@main
        id: build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image-ref: ${{ inputs.image-ref }}
          tags: ${{ inputs.tags }}
          build-args: ${{ inputs.build-args }}
          push: ${{ inputs.push }}
    outputs:
      image_name: ${{ steps.build.outputs.image-name }}

  sbom:
    runs-on: ubuntu-latest
    if: ${{ inputs.push == 'true' }}
    needs: build
    permissions:
      actions: read
      contents: write
      security-events: write
    steps:
      - uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
        with:
          image-ref: ${{ needs.image.outputs.image_name }}
          format: github
          output: dependency-results.sbom.json
          github-pat: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: trivy-sbom-report
          path: "${{ github.workspace }}/dependency-results.sbom.json"
